Inventory Control System/Inventory Control System/Controllers/ProductCategoryController.cs
using AutoMapper;
using InventoryControlSystem.Entity;
using InventoryControlSystem.Service.Contract;
using InventoryControlSystem.ViewModel;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventoryControlSystem.Controllers
{
    public class ProductCategoryController : Controller
    {
        private readonly IProductCategoryService _productCategoryService;

        public ProductCategoryController(IProductCategoryService productCategoryService)
        {
            _productCategoryService = productCategoryService;
        }

        // GET: Brand
        public ActionResult Index()
        {
            var productCategories = _productCategoryService.GetAll();
            var productCategoriesList = Mapper.Map<IEnumerable<ProductCategory>, IEnumerable<ProductCategoryViewModel>>(productCategories);
            return View(productCategoriesList);
        }

        // GET: Brand/Details/5
        public ActionResult Details(Guid id)
        {
            var productCategory = _productCategoryService.GetById(id);
            var productCategoryModel = Mapper.Map<ProductCategory, ProductCategoryViewModel>(productCategory);
            return View(productCategoryModel);
        }

        // GET: Brand/Create
        public ActionResult Create()
        {
            var model = new ProductCategoryViewModel();
            return View(model);
        }

        // POST: Brand/Create
        [HttpPost]
        public ActionResult Create(ProductCategoryViewModel model)
        {

            try
            {
                // TODO: Add insert logic here
                if (!ModelState.IsValid)
                    return View(model);
                var productCategory = Mapper.Map<ProductCategoryViewModel, ProductCategory>(model);
                productCategory.CreatedTime = DateTime.Now;
                productCategory.UserId = User.Identity.GetUserId();
                _productCategoryService.Insert(productCategory);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return View(model);
            }
        }

        // GET: Brand/Edit/5
        public ActionResult Edit(Guid id)
        {

            var productCategory = _productCategoryService.GetById(id);
            var productCategoryModel = Mapper.Map<ProductCategory, ProductCategoryViewModel>(productCategory);
            return View(productCategoryModel);
        }

        // POST: Brand/Edit/5
        [HttpPost]
        public ActionResult Edit(ProductCategoryViewModel model)
        {

            try
            {
               
                if(!ModelState.IsValid)
                {
                    return View(model);
                }
                var productCategory = Mapper.Map<ProductCategoryViewModel, ProductCategory>(model);
                _productCategoryService.Update(productCategory);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return View();
            }
        }

        // GET: Brand/Delete/5
        public ActionResult Delete(Guid id)
        {
            try
            {
                if (id == Guid.Empty)
                    return RedirectToAction("Index");
                var productCategory = _productCategoryService.GetById(id);
                _productCategoryService.Delete(productCategory);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return View();
            }
        }

        // POST: Brand/Delete/5
        [HttpPost]
        public ActionResult Delete(Guid id, ProductCategory model)
        {
            try
            {
                if (id == null)
                    return RedirectToAction("Index");
                var productCategory = _productCategoryService.GetById(id);
                _productCategoryService.Delete(productCategory);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return View();
            }
        }
    }
}

Inventory Control System/Inventory Control System/Views/ProductCategory/Create.cshtml
@model InventoryControlSystem.ViewModel.ProductCategoryViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="content-header">
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-6">
            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title">Create ProductCategory</h3>
                </div>
                @using (Html.BeginForm("Create", "ProductCategory", FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="box-body">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.CatCode, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.CatCode, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.CatCode, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.PCategory, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.PCategory, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.PCategory, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                            </div>
                        </div>
                       
                    </div>
                    <div class="box-footer">
                        <div class="col-md-offset-2 col-md-10">
                           <input type="submit" value="Create" class="pull-right btn btn-default" />
                        </div>
                    </div>

                }

            </div>
        </div>
    </div>

</section>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Inventory Control System/Inventory Control System/Views/ProductCategory/Delete.cshtml
@model InventoryControlSystem.ViewModel.ProductCategoryViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ProductCategoryViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CatCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CatCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PCategory)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PCategory)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedTime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Inventory Control System/Inventory Control System/Views/ProductCategory/Details.cshtml
@model InventoryControlSystem.ViewModel.ProductCategoryViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>ProductCategoryViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CatCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CatCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PCategory)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PCategory)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedTime)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Inventory Control System/Inventory Control System/Views/ProductCategory/Edit.cshtml
@model InventoryControlSystem.ViewModel.ProductCategoryViewModel
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="content-header">
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-offset-3 col-md-6">
            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title">Edit ProductCategory</h3>
                </div>
                @using (Html.BeginForm("Edit", "ProductCategory", FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="box-body">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id)
                        @Html.HiddenFor(model => model.CreatedTime)
                        <div class="form-group">
                            @Html.LabelFor(model => model.CatCode, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.CatCode, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.CatCode, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.PCategory, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.PCategory, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.PCategory, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                            </div>
                        </div>

                    </div>
                        <div class="box-footer">
                            <div class="form-group ">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Update" class="pull-right btn btn-warning" />
                                </div>
                            </div>
                        </div>
                }
            </div>
        </div>
    </div>
</section>
@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Inventory Control System/Inventory Control System/Views/ProductCategory/Index.cshtml
@model IEnumerable<InventoryControlSystem.ViewModel.ProductCategoryViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="content-header">
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title"> FinanicalYear</h3>
                </div>
                <div class="box-body">
                    <table class="table table-bordered table-striped datatable">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.CatCode)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.PCategory)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Description)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CreatedTime)
                                </th>
                                <th></th>
                            </tr>
                            </thead>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CatCode)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.PCategory)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Description)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CreatedTime)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                        @*   @Html.ActionLink("Details", "Details", new { id = item.Id }) |*@
                                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                                    </td>
                                </tr>
                            }
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>