Inventory Control System/Inventory Control System/Controllers/MeasurementController.cs
using AutoMapper;
using InventoryControlSystem.Entity;
using InventoryControlSystem.Service.Contract;
using InventoryControlSystem.ViewModel;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventoryControlSystem.Controllers
{
    public class MeasurementController : Controller
    {
        private readonly IMeasurementService _measurementService;

        public MeasurementController(IMeasurementService measurementService)
        {
            _measurementService = measurementService;
        }

        // GET: Brand
        public ActionResult Index()
        {
            var measurements = _measurementService.GetAll();
            var measurementsList = Mapper.Map<IEnumerable<Measurement>, IEnumerable<MeasurementViewModel>>(measurements);
            return View(measurementsList);
        }

        // GET: Brand/Details/5
        public ActionResult Details(Guid id)
        {
            var measurement = _measurementService.GetById(id);
            var measurementModel = Mapper.Map<Measurement, MeasurementViewModel>(measurement);
            return View(measurementModel);
        }

        // GET: Brand/Create
        public ActionResult Create()
        {
            var model = new MeasurementViewModel();
            return View(model);
        }

        // POST: Brand/Create
        [HttpPost]
        public ActionResult Create(MeasurementViewModel model)
        {

            try
            {
                // TODO: Add insert logic here
                if (!ModelState.IsValid)
                    return View(model);
                var measurement = Mapper.Map<MeasurementViewModel, Measurement>(model);
                measurement.CreatedTime = DateTime.Now;
                measurement.UserId = User.Identity.GetUserId();
                _measurementService.Insert(measurement);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View(model);
            }
        }

        // GET: Brand/Edit/5
        public ActionResult Edit(Guid id)
        {

            var measurement = _measurementService.GetById(id);
            var measurementModel = Mapper.Map<Measurement, MeasurementViewModel>(measurement);
            return View(measurementModel);
        }

        // POST: Brand/Edit/5
        [HttpPost]
        public ActionResult Edit(MeasurementViewModel model)
        {

            try
            {
                if(!ModelState.IsValid)
                    return View(model);
                var measurement = Mapper.Map<MeasurementViewModel, Measurement>(model);
                _measurementService.Update(measurement);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        // GET: Brand/Delete/5
        public ActionResult Delete(Guid id)
        {
            try
            {
                if (id == Guid.Empty)
                    return RedirectToAction("Index");
                var measurement = _measurementService.GetById(id);
                _measurementService.Delete(measurement);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return View();
            }
        }

        // POST: Brand/Delete/5
        [HttpPost]
        public ActionResult Delete(Guid id, Measurement model)
        {
            try
            {
                if (id == null)
                    return RedirectToAction("Index");
                var measurement = _measurementService.GetById(id);
                _measurementService.Delete(measurement);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return View();
            }
        }
    }
}

Inventory Control System/Inventory Control System/Views/Measurement/Create.cshtml
@model InventoryControlSystem.ViewModel.MeasurementViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="content-header">
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-6">
            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title">Create Measurement</h3>
                </div>
                @using (Html.BeginForm("Create", "Measurement", FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="box-body">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.ShortCode, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.ShortCode, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.ShortCode, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.MeasurementName, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.MeasurementName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.MeasurementName, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.ConversionValue, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.ConversionValue, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.ConversionValue, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.EquivalentMeasurement, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.EquivalentMeasurement, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.EquivalentMeasurement, "", new { @class = "text-danger" })
                            </div>
                        </div>
                      
                    </div>
                    <div class="box-footer">
                        <div class="col-md-offset-2 col-md-8">
                           <input type="submit" value="Create" class="pull-right btn btn-default" />
                        </div>
                    </div>

                }

            </div>
        </div>
    </div>

</section>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Inventory Control System/Inventory Control System/Views/Measurement/Delete.cshtml
@model InventoryControlSystem.ViewModel.MeasurementViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MeasurementViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ShortCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShortCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MeasurementName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MeasurementName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConversionValue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConversionValue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EquivalentMeasurement)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EquivalentMeasurement)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedTime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Inventory Control System/Inventory Control System/Views/Measurement/Details.cshtml
@model InventoryControlSystem.ViewModel.MeasurementViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>MeasurementViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ShortCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShortCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MeasurementName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MeasurementName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConversionValue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConversionValue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EquivalentMeasurement)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EquivalentMeasurement)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedTime)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Inventory Control System/Inventory Control System/Views/Measurement/Edit.cshtml
@model InventoryControlSystem.ViewModel.MeasurementViewModel
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="content-header">
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-offset-3 col-md-6">
            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title">Edit Measurement</h3>
                </div>
                @using (Html.BeginForm("Edit", "Measurement", FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="box-body">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id)
                        @Html.HiddenFor(model => model.CreatedTime)
                        <div class="form-group">
                            @Html.LabelFor(model => model.ShortCode, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.ShortCode, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.ShortCode, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.MeasurementName, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.MeasurementName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.MeasurementName, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.ConversionValue, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.ConversionValue, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.ConversionValue, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.EquivalentMeasurement, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-8">
                                @Html.EditorFor(model => model.EquivalentMeasurement, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.EquivalentMeasurement, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                        <div class="box-footer">
                            <div class="form-group ">
                                <div class="col-md-offset-2 col-md-8">
                                    <input type="submit" value="Update" class="pull-right btn btn-warning" />
                                </div>
                            </div>
                        </div>
                }
            </div>
        </div>
    </div>
</section>
@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Inventory Control System/Inventory Control System/Views/Measurement/Index.cshtml
@model IEnumerable<InventoryControlSystem.ViewModel.MeasurementViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content-header">
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title"> Measurement</h3>
                </div>
                <div class="box-body">
                    <table class="table table-bordered table-striped datatable">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.ShortCode)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.MeasurementName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.ConversionValue)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.EquivalentMeasurement)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CreatedTime)
                                </th>
                                <th></th>
                            </tr>
                            </thead>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ShortCode)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.MeasurementName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ConversionValue)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.EquivalentMeasurement)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CreatedTime)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                        @*   @Html.ActionLink("Details", "Details", new { id = item.Id }) |*@
                                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                                    </td>
                                </tr>
                            }
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>