Inventory Control System/Inventory Control System/Controllers/DesignationController.cs
using AutoMapper;
using InventoryControlSystem.Entity;
using InventoryControlSystem.Service.Contract;
using InventoryControlSystem.ViewModel;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventoryControlSystem.Controllers
{
    public class DesignationController : Controller
    {
        private readonly IDesignationService _designationService;

        public DesignationController(IDesignationService designationService)
        {
            _designationService = designationService;
        }
        // GET: Designation
        public ActionResult Index()
        {
            var desgination = _designationService.GetAll().Select(x => new
             DesignationViewModel
            {
                Id=x.Id,
                Name = x.Name,
                CreatedTime = x.CreatedTime
            }).ToList();
            //var result = Mapper.Map<DesignationViewModel>(desgination);
            return View(desgination);
        }

        // GET: Designation/Details/5
        public ActionResult Details(Guid id)
        {
            return View();
        }

        // GET: Designation/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Designation/Create
        [HttpPost]
        public ActionResult Create(DesignationViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View(model);
                var desg = Mapper.Map<DesignationViewModel, Designation>(model);
                desg.UserId = User.Identity.GetUserId();
                desg.CreatedTime = DateTime.Now;
                _designationService.Insert(desg);
                return RedirectToAction("Index");
               
            }
            catch(Exception ex)
            {
                return View(model);
            }
        }

        // GET: Designation/Edit/5
        public ActionResult Edit(Guid id)
        {
            var des = _designationService.GetById(id);
            var desModel = Mapper.Map<Designation, DesignationViewModel>(des);
            return View(desModel);
        }

        // POST: Designation/Edit/5
        [HttpPost]
        public ActionResult Edit(Guid id, DesignationViewModel model)
        {
            try
            {
                //if (id == null)
                //    return RedirectToAction("Index");
                var des = Mapper.Map<DesignationViewModel, Designation>(model);
                _designationService.Update(des);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return View();
            }
        }

        // GET: Designation/Delete/5
        public ActionResult Delete(Guid id)
        {
            try
            {
                if (id==Guid.Empty)
                    return RedirectToAction("Index");
                var des = _designationService.GetById(id);
                _designationService.Delete(des);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return View();
            }
        }

        // POST: Designation/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Inventory Control System/Inventory Control System/Views/Designation/Create.cshtml
@model InventoryControlSystem.ViewModel.DesignationViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content-header">
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-6">
            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title">Create Designation</h3>
                </div>
                @using (Html.BeginForm("Create", "Designation", FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="">
                       
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <div class="col-md-offset-2 col-md-9">
                           <input type="submit" value="Create" class="pull-right btn btn-primary" />
                        </div>
                    </div>

                }

            </div>
        </div>
    </div>

</section>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Inventory Control System/Inventory Control System/Views/Designation/Edit.cshtml
@model InventoryControlSystem.ViewModel.DesignationViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content-header">
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-offset-3 col-md-6">
            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title">Edit Designation</h3>
                </div>
                @using (Html.BeginForm("Edit", "Designation", FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.Id)
                    @Html.HiddenFor(model => model.CreatedTime)
                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <div class="form-group ">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Update" class="pull-right btn btn-warning" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>
@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Inventory Control System/Inventory Control System/Views/Designation/Index.cshtml
@model IEnumerable<InventoryControlSystem.ViewModel.DesignationViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content-header">
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title"> Designation</h3>
                </div>
                <div class="box-body">
                    <table class="table table-bordered table-striped datatable">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Name)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CreatedTime)
                                </th>

                                <th></th>
                            </tr>
                            </thead>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CreatedTime)
                                    </td>

                                    <td>
                                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                        @*@Html.ActionLink("Details", "Details", new { id = item.Id }) |*@
                                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                                    </td>
                                </tr>
                            }


                    </table>
                </div>
            </div>
        </div>
    </div>
</section>