Inventory Control System/Inventory Control System/Controllers/OrganisationController.cs
using AutoMapper;
using InventoryControlSystem.Entity;
using InventoryControlSystem.Service.Contract;
using InventoryControlSystem.ViewModel;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventoryControlSystem.Controllers
{
    public class OrganisationController : Controller
    {
        private readonly IOrganisationService _organisationService;
        private readonly IStateService _stateService;
        public OrganisationController(IOrganisationService organisationService,IStateService stateService)
        {
            _organisationService = organisationService;
            _stateService = stateService;
        }
        // GET: Organisation
        public ActionResult Index()
        {
            var orgnizations = _organisationService.GetAll();
            var orgnizationModelList = Mapper.Map<IEnumerable<Organisation>, IEnumerable<OrganisationViewModel>>(orgnizations);
            return View(orgnizationModelList);
        }

        // GET: Organisation/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Organisation/Create
        public ActionResult Create()
        {
            ViewBag.States = _stateService.GetAll();
            return View();
        }

        // POST: Organisation/Create
        [HttpPost]
        public ActionResult Create(OrganisationViewModel model)
        {
            try
            {
                ViewBag.States = _stateService.GetAll();
                if (!ModelState.IsValid)
                    return View(model);
                var org = Mapper.Map<OrganisationViewModel, Organisation>(model);
                org.UserId = User.Identity.GetUserId();
                org.CreatedTime = DateTime.Now;
                _organisationService.Insert(org);
                return RedirectToAction("Index");
            }
            catch
            {
              
                return View();
            }
        }

        // GET: Organisation/Edit/5
        public ActionResult Edit(Guid id)
        {
            ViewBag.States = _stateService.GetAll();
            var org = _organisationService.GetById(id);
            var orgModel = Mapper.Map<Organisation, OrganisationViewModel>(org);
            return View(orgModel);
        }

        // POST: 
        [HttpPost]
        public ActionResult Edit(Guid id, OrganisationViewModel model)
        {
            try
            {
                if(!ModelState.IsValid)
                {
                    ViewBag.States = _stateService.GetAll();
                    return View(model);
                }
                var org = Mapper.Map<OrganisationViewModel, Organisation>(model);
                _organisationService.Update(org);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return View();
            }
        }

        // GET: 
        public ActionResult Delete(Guid id)
        {
            try
            {
                if (id == null)
                    return RedirectToAction("Index");
                var org = _organisationService.GetById(id);
                _organisationService.Delete(org);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View();
            }
        }

       
    }
}

Inventory Control System/Inventory Control System/Views/Organisation/Create.cshtml
@model InventoryControlSystem.ViewModel.OrganisationViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="content-header">
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-6">
            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title">Create Qrganisation</h3>
                </div>
                @using (Html.BeginForm("Create", "Organisation", FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="box-body">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.OrgName, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.OrgName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.OrgName, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.CSTNo, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.CSTNo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.CSTNo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.RegistrationNo, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.RegistrationNo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.RegistrationNo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.ContactPerson, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.ContactPerson, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.ContactPerson, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.StateId, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.DropDownListFor(model => model.StateId, new SelectList(ViewBag.States, "Id", "Name"), new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.StateId, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.MobileNo, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.MobileNo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.MobileNo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.PhoneNo, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.PhoneNo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.PhoneNo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.PINno, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.PINno, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.PINno, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.EmailId, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.EmailId, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.EmailId, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Website, htmlAttributes: new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.Website, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Website, "", new { @class = "text-danger" })
                            </div>
                        </div>

                       
                    </div>
                    <div class="box-footer">
                        <div class="col-md-offset-2 col-md-9">
                           <input type="submit" value="Create" class="pull-right btn btn-default" />
                        </div>
                    </div>

                }

            </div>
        </div>
    </div>

</section>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Inventory Control System/Inventory Control System/Views/Organisation/Edit.cshtml
@model InventoryControlSystem.ViewModel.OrganisationViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content-header">
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-offset-3 col-md-6">
            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title">Edit Organisation</h3>
                </div>
                @using (Html.BeginForm("Edit", "Organisation", FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.Id)
                    @Html.HiddenFor(model => model.CreatedTime)
                    <div class="box-body">


                        <div class="form-group">
                            @Html.LabelFor(model => model.OrgName, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.OrgName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.OrgName, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.CSTNo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.CSTNo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.CSTNo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.RegistrationNo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.RegistrationNo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.RegistrationNo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.ContactPerson, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.ContactPerson, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.ContactPerson, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.StateId, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.StateId, new SelectList(ViewBag.States, "Id", "Name"), new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.StateId, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.MobileNo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.MobileNo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.MobileNo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.PhoneNo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.PhoneNo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.PhoneNo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.PINno, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.PINno, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.PINno, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.EmailId, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.EmailId, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.EmailId, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Website, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Website, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Website, "", new { @class = "text-danger" })
                            </div>
                        </div>

                    </div>
                    <div class="box-footer">
                        <div class="form-group ">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Update" class="pull-right btn btn-warning" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>
@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Inventory Control System/Inventory Control System/Views/Organisation/Index.cshtml
@model IEnumerable<InventoryControlSystem.ViewModel.OrganisationViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="content-header">
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
</section>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-info">
                <div class="box-header">
                    <h3 class="box-title"> Organisation</h3>
                </div>
                <div class="box-body">
                    <table class="table table-bordered table-striped datatable">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.OrgName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CSTNo)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.RegistrationNo)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.ContactPerson)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Address)
                                </th>

                                <th>
                                    @Html.DisplayNameFor(model => model.City)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.MobileNo)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.PhoneNo)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.PINno)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.EmailId)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Website)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CreatedTime)
                                </th>
                                <th></th>
                            </tr>
                            </thead>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.OrgName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CSTNo)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.RegistrationNo)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ContactPerson)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Address)
                                    </td>

                                    <td>
                                        @Html.DisplayFor(modelItem => item.City)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.MobileNo)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.PhoneNo)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.PINno)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.EmailId)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Website)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CreatedTime)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Edit", "Edit", new { id = @item.Id }) |
                                        @* @Html.ActionLink("Details", "Details", new { id = item.Id }) |*@
                                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                                    </td>
                                </tr>
                            }

                    </table>
                </div>
            </div>
        </div>
    </div>
</section>